### ISSUE TITLE
Language selection does not switch the nav-bar contents

### ISSUE THREAD

**Issue by wanseob** [ethcon-kr/genesis.ethcon.kr#12]
![image](https://user-images.githubusercontent.com/8542397/55213959-6e149680-5238-11e9-9b97-1f544386a961.png)

**Comment by HeesungB** [comment]
한글       /        영문
왼쪽 타이틀 :  이드콘 한국 / ETHCON KOREA
발표신청 :      발표신청 /  Apply Presentation
참가신청 :      참가신청 / Participate in
스폰서 신청 : 스폰서신청 / Apply Sponsor
MY ETHCON : 내 티켓 / MY ETHCON
LANGUAGE  : 언어 / LANGUAGE

이 사항에 대해서 조금더 유연한 영어 번역 및 한국어 단어가 필요합니다 ㅜ
