### ISSUE TITLE
facebook pixel code

### ISSUE THREAD

**Issue by wanseob** [ethcon-kr/genesis.ethcon.kr#20]

**Comment by andrewkim-kr** [comment]
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '267874750832148');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=267874750832148&ev=PageView&noscript=1"
/></noscript>

**Comment by andrewkim-kr** [comment]
</head> 바로 위에 넣으면 됩니다!
